# Generated by Django 4.1.6 on 2023-02-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(choices=[('L', 'Leisure'), ('B', 'Business')], default='L', max_length=1)),
                ('highlight', models.TextField(max_length=250)),
                ('road_trip', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.country')),
            ],
        ),
    ]
