# Generated by Django 4.1.6 on 2023-02-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_visit_roadtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='roadtrip',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
