# Generated by Django 4.1.6 on 2023-02-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
