# Generated by Django 4.1.6 on 2023-02-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_visit_end_date_alter_visit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
