# Generated by Django 4.1.6 on 2023-02-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cities',
            field=models.ManyToManyField(to='main_app.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.TextField(max_length=250),
        ),
    ]
