# Generated by Django 4.1.6 on 2023-02-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_visit_end_date_alter_visit_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='road_trip',
        ),
    ]
