# Generated by Django 4.1.6 on 2023-02-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_city_highlight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='Trip',
        ),
    ]
