# Generated by Django 4.1.6 on 2023-02-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_trip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('J', 'Journey'), ('S', 'Stay'), ('A', 'Activity')], max_length=1)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_location', models.CharField(blank=True, max_length=100, null=True)),
                ('journey_type', models.CharField(blank=True, choices=[('A', 'By Air'), ('S', 'By Sea'), ('D', 'By Road'), ('L', 'By Rail'), ('O', 'Other')], max_length=1, null=True)),
                ('distance', models.CharField(blank=True, choices=[('M', 'miles'), ('K', 'kilometres')], max_length=1, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('stay_type', models.CharField(blank=True, choices=[('H', 'Hotel'), ('G', 'Guesthouse'), ('C', 'Campsite'), ('W', 'Wild Camping'), ('O', 'Other')], max_length=1, null=True)),
                ('stay_name', models.CharField(blank=True, help_text='The name of the hotel, campsite, guesthouse or a description of your wild camping', max_length=100, null=True)),
                ('stay_location', models.CharField(blank=True, help_text='Save the longitude and latitude to help yourself and others find your stay again!', max_length=100, null=True)),
                ('stay_map', models.CharField(blank=True, help_text='Save a map link to help yourself and others find your stay again!', max_length=300, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('H', 'Hotel'), ('G', 'Guesthouse'), ('C', 'Campsite'), ('W', 'Wild Camping'), ('O', 'Other')], max_length=1, null=True)),
                ('activity_description', models.TextField(blank=True, max_length=300, null=True)),
                ('organiser_type', models.CharField(blank=True, choices=[('S', 'Self-Organised'), ('T', 'Tour Operator'), ('G', 'Guide')], max_length=1, null=True)),
                ('organiser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organiser_email', models.CharField(blank=True, max_length=100, null=True)),
                ('organiser_telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('segment_country_start', models.ManyToManyField(max_length=100, to='main_app.country')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='countries',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='trip',
            name='segments',
            field=models.ManyToManyField(to='main_app.segment'),
        ),
    ]
