# Generated by Django 4.1.6 on 2023-02-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_segment_remove_trip_cities_remove_trip_countries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='duration',
            new_name='duration_hrs',
        ),
        migrations.AddField(
            model_name='segment',
            name='distance_measurement',
            field=models.CharField(blank=True, choices=[('M', 'miles'), ('K', 'kilometres')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
