# Generated by Django 4.1.6 on 2023-02-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital_city',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
    ]
