# Generated by Django 4.1.6 on 2023-02-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_country_capital_city_remove_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='segments',
        ),
        migrations.AddField(
            model_name='segment',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.trip'),
            preserve_default=False,
        ),
    ]
